/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bars.SideBar;
import java.awt.Color;
import java.io.IOException;
import java.lang.System;
import java.nio.file.DirectoryStream;
import java.nio.file.Path;
import java.nio.file.Files;
import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JLabel;
import java.awt.GridLayout;

/**
 *
 * @author gzy
 */
public class FileTreeBar extends javax.swing.JPanel {

    /**
     * Creates new form FileTreeBar
     */
    public FileTreeBar() {
        initComponents();
        mainScrollPane.setOpaque(false);
        mainScrollPane.getViewport().setOpaque(false);
        initComponentsManually();
    }
    
    private void searchDir(Path Dir, String Gap){
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(Dir)) {
            for (Path file : stream) {
                fileLabels.add(new JLabel(Gap.concat(Dir.relativize(file).toString())));
                fileLabels.get(fileLabels.size() - 1).setForeground(Color.WHITE);
                File fileOrDir = new File(file.toString());
                if(fileOrDir.isDirectory()){
                    searchDir(Paths.get(file.toString()), Gap.concat("  "));
                }
            }
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    
    private void initComponentsManually()
    {
        fileLabels = new ArrayList<>();
        Path projectDirectory = Paths.get(System.getProperty("user.dir"));
        searchDir(projectDirectory, "");
        for (int i = 0; i < fileLabels.size(); i++) {
            mainPanel.add(fileLabels.get(i));
        }
        mainPanel.setLayout(new GridLayout(fileLabels.size(),1));
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(196, 300));

        titleLabel.setForeground(new java.awt.Color(238, 238, 238));
        titleLabel.setText("File Tree");

        mainScrollPane.setOpaque(false);
        mainScrollPane.setPreferredSize(new java.awt.Dimension(196, 300));
        mainScrollPane.setSize(new java.awt.Dimension(196, 300));

        mainPanel.setOpaque(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        mainScrollPane.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//
//    public void setOpaque(boolean cond){
//        mainScrollPane.setOpaque(cond);
//        mainScrollPane.getViewport().setOpaque(cond);
//    }

    private ArrayList<JLabel> fileLabels;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
