/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bars.SideBar;
import Start.*;

/**
 *
 * @author gzy
 */
public class SideBar extends javax.swing.JPanel {

    /**
     * Creates new form SideBar
     * @param par
     */
    public SideBar(MainWindow par) {
        initComponents();
        parentWindow = par;
        initComponentsManually();
    }
    
    private void initComponentsManually(){
        fileTreeBar = new FileTreeBar();
        titleTreeBar = new TitleTreeBar(parentWindow);
        gitTreeBar = new GitTreeBar();
        fileTreeBar.setBounds(0, 0, 196, 300);
        fileTreeBar.setVisible(true);
//        fileTreeBar.setOpaque(false);
        titleTreeBar.setBounds(0, 300, 196, 300);
        titleTreeBar.setVisible(true);
//        titleTreeBar.setOpaque(false);
        gitTreeBar.setBounds(0, 600, 196, 278);
        gitTreeBar.setVisible(true);
//        gitTreeBar.setOpaque(false);
        mainSideBarPanel.add(fileTreeBar);
        mainSideBarPanel.add(gitTreeBar);
        mainSideBarPanel.add(titleTreeBar);
        mainSideBarPanel.revalidate();
        mainSideBarPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSideBarPanel = new javax.swing.JPanel();

        setOpaque(false);

        mainSideBarPanel.setOpaque(false);
        mainSideBarPanel.setPreferredSize(new java.awt.Dimension(196, 878));
        mainSideBarPanel.setSize(new java.awt.Dimension(196, 878));

        javax.swing.GroupLayout mainSideBarPanelLayout = new javax.swing.GroupLayout(mainSideBarPanel);
        mainSideBarPanel.setLayout(mainSideBarPanelLayout);
        mainSideBarPanelLayout.setHorizontalGroup(
            mainSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        mainSideBarPanelLayout.setVerticalGroup(
            mainSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private FileTreeBar fileTreeBar;
    private TitleTreeBar titleTreeBar;
    private GitTreeBar gitTreeBar;
    private MainWindow parentWindow;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainSideBarPanel;
    // End of variables declaration//GEN-END:variables
}
