/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Start;
import Bars.ButtonBars.MainWindowButtonBar;
import java.awt.Color;

/**
 *
 * @author gzy
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initComponentsManually();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        MainLayer = new javax.swing.JLayeredPane();
        coverPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        workspaceMenu = new javax.swing.JMenu();
        openNewWindowMenutem = new javax.swing.JMenuItem();
        closeAppMenuItem = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cpyMemuItem = new javax.swing.JMenuItem();
        cutMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        appendMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        findMenuItem = new javax.swing.JMenuItem();
        replaceMenuItem = new javax.swing.JMenuItem();
        GitMenu = new javax.swing.JMenu();
        settingsMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coverPanel.setBackground(new Color(0,0,0,75));

        javax.swing.GroupLayout coverPanelLayout = new javax.swing.GroupLayout(coverPanel);
        coverPanel.setLayout(coverPanelLayout);
        coverPanelLayout.setHorizontalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1390, Short.MAX_VALUE)
        );
        coverPanelLayout.setVerticalGroup(
            coverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        MainLayer.add(coverPanel);
        coverPanel.setBounds(0, 0, 1390, 920);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_background.png"))); // NOI18N
        MainLayer.add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1390, 920);

        workspaceMenu.setText("Workspace");

        openNewWindowMenutem.setText("Open New Window");
        openNewWindowMenutem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNewWindowMenutemActionPerformed(evt);
            }
        });
        workspaceMenu.add(openNewWindowMenutem);

        closeAppMenuItem.setText("Close App");
        workspaceMenu.add(closeAppMenuItem);

        mainMenuBar.add(workspaceMenu);

        fileMenu.setText("File");

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Sace As");
        fileMenu.add(saveAsMenuItem);

        importMenuItem.setText("Import");
        fileMenu.add(importMenuItem);

        exportMenuItem.setText("Export");
        fileMenu.add(exportMenuItem);

        mainMenuBar.add(fileMenu);

        editMenu.setText("Edit Block");

        cpyMemuItem.setText("Copy");
        cpyMemuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpyMemuItemActionPerformed(evt);
            }
        });
        editMenu.add(cpyMemuItem);

        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        appendMenuItem.setText("Append");
        editMenu.add(appendMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        findMenuItem.setText("Find");
        editMenu.add(findMenuItem);

        replaceMenuItem.setText("Replace");
        editMenu.add(replaceMenuItem);

        mainMenuBar.add(editMenu);

        GitMenu.setText("Git");
        mainMenuBar.add(GitMenu);

        settingsMenu.setText("Settings");
        mainMenuBar.add(settingsMenu);

        jMenu1.setText("About");
        mainMenuBar.add(jMenu1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsManually(){
        mainButtonBar = new Bars.ButtonBars.MainWindowButtonBar();
        mainButtonBar.setBounds(0, 0, 1400, 41);
        MainLayer.add(mainButtonBar);
        MainLayer.moveToFront(mainButtonBar);
    }
    
    private void openNewWindowMenutemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNewWindowMenutemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openNewWindowMenutemActionPerformed

    private void cpyMemuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpyMemuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpyMemuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mainWindowObj = new MainWindow();
                mainWindowObj.setVisible(true);
                mainWindowObj.setBounds(0, 0, 1400, 960);
            }
        });
    }
    
    private Bars.ButtonBars.MainWindowButtonBar mainButtonBar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu GitMenu;
    private javax.swing.JLayeredPane MainLayer;
    private javax.swing.JMenuItem appendMenuItem;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JMenuItem closeAppMenuItem;
    private javax.swing.JPanel coverPanel;
    private javax.swing.JMenuItem cpyMemuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem findMenuItem;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem openNewWindowMenutem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem replaceMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenu workspaceMenu;
    // End of variables declaration//GEN-END:variables
}
