/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Blocks;

import javax.swing.JTextPane;

import Bars.ButtonBars.*;
import Start.*;
import javax.swing.undo.UndoManager;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.*;
import java.awt.Color;

/**
 *
 * @author gzy
 */
public class CommonTextBlock extends javax.swing.JPanel{

    /**
     * Creates new form CommonTextBlock
     * @param parentWindow
     */
    public CommonTextBlock(MainWindow parentWindow, BlockType curBlockType) {
        initComponents();
        parentMainWindow = parentWindow;
        initComponentsManually(curBlockType);
        mainInputTextPane.setOpaque(false);
    }
    
    public boolean setID(int ID){
        return inputTextBlockBasic.setID(ID);
    }
    
    public int getID(){
        return inputTextBlockBasic.getID();
    }
    
    public boolean changeBlock(BlockType newBlockType){
        return parentMainWindow.changeBlock(inputTextBlockBasic.getID(), newBlockType);
    }
    
    public boolean whetherCanUndo(){
        return undoManager.canUndo();
    }
    
    public boolean whetherCanRedo(){
        return undoManager.canRedo();
    }
    
    public boolean undoOperation(){
        if(!undoManager.canUndo()){
            return false;
        }
        undoManager.undo();
        return true;
    }
    
    public boolean redoOperation(){
        if(!undoManager.canRedo()){
            return false;
        }
        undoManager.redo();
        return true;
    }
    
    public javax.swing.JTextPane getMainTextPane(){
        return mainInputTextPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainInputScrollPane = new javax.swing.JScrollPane();
        mainInputTextPane = new javax.swing.JTextPane();
        lineNumScrollPane = new javax.swing.JScrollPane();
        lineNumTextPane = new javax.swing.JTextPane();

        setBackground(new Color(0,0,0,0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 300));

        mainInputScrollPane.setOpaque(false);

        mainInputTextPane.setBackground(new Color(255, 255, 255,0));
        mainInputTextPane.setForeground(new java.awt.Color(255, 255, 255));
        mainInputTextPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainInputTextPaneKeyTyped(evt);
            }
        });
        mainInputScrollPane.setViewportView(mainInputTextPane);

        lineNumScrollPane.setOpaque(false);

        lineNumTextPane.setBackground(new Color(255,255,255,0));
        lineNumTextPane.setForeground(new java.awt.Color(255, 255, 255));
        lineNumScrollPane.setViewportView(lineNumTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lineNumScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lineNumScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(mainInputScrollPane)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainInputTextPaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainInputTextPaneKeyTyped
        // TODO add your handling code here:
        mainInputTextPane.setBackground(new Color(255,255,255,0));
        mainInputTextPane.revalidate();
        mainInputTextPane.repaint();
    }//GEN-LAST:event_mainInputTextPaneKeyTyped

    private void initComponentsManually(BlockType curBlockType){
        lineNumTextPane.setContentType("text/html");
        inputTextBlockBasic = new BlockBasic();
        mainInputScrollPane.getViewport().setOpaque(false);
        lineNumScrollPane.getViewport().setOpaque(false);
        initCommonTextButtonBar(curBlockType);
        commonTextButtonBar.setBounds(0, 0, 1200, 62);
        this.add(commonTextButtonBar);
        mainInputTextPane.getDocument().addUndoableEditListener(new UndoableEditListener(){
            public void undoableEditHappened(UndoableEditEvent e){
                undoManager.addEdit(e.getEdit());
            }
        });
        DocumentListener repaintDocumentListener = new RepaintDocumentListener(this);
        mainInputTextPane.getDocument().addDocumentListener(repaintDocumentListener);
        inputTextBlockBasic.setMasterInputBlock(this);
    }
    
    public void initCommonTextButtonBar(BlockType thisBlockType){
        switch(thisBlockType){
            case COMMONTEXT->{
                commonTextButtonBar = new CommonTextButtonBar(this);
            }
            case CODE->{
                commonTextButtonBar = new CodeButtonBar(this);
            }
            case FORMULA->{
                commonTextButtonBar = new FormulaButtonBar(this);
            }
            case HYPERTEXT->{
                commonTextButtonBar = new HyperTextButtonBar(this);
            }
            case MARKDOWN->{
                commonTextButtonBar = new MarkdownButtonBar(this);
            }
            case TITLE->{
                commonTextButtonBar = new TitleButtonBar(this);
            }
        }
    }
    
    public BlockBasic getBlockBasic(){
        return inputTextBlockBasic;
    }
    
    public int getLineCount(JTextPane textPane){
        int totalCharacters = textPane.getText().length(); 
        int lineCount = (totalCharacters == 0) ? 1 : 0;

        try {
           int offset = totalCharacters; 
           while (offset > 0) {
              offset = Utilities.getRowStart(textPane, offset) - 1;
              lineCount++;
           }
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
        return lineCount;
    }
    
    public void checkLineNumUpdate(){
        int curLineNum = getLineCount(mainInputTextPane);
        int displayLineNum = getLineCount(lineNumTextPane);
        StringBuilder sb = new StringBuilder();
        if(curLineNum != displayLineNum){
            for(int i = 0; i < curLineNum; i++){
                sb.append(Integer.toString(i).concat("<br>"));
            }
        }
        lineNumTextPane.setText(sb.toString());
    }
    
    
    public void repaintMainPane(){
        mainInputTextPane.setBackground(new Color(255,255,255,0));
        mainInputTextPane.revalidate();
        mainInputTextPane.repaint();
        lineNumTextPane.setBackground(new Color(255,255,255,0));
        lineNumTextPane.revalidate();
        lineNumTextPane.repaint();
        revalidate();
        repaint();
        parentMainWindow.repaintMainPane();
        checkLineNumUpdate();
    }
    
    public class RepaintDocumentListener implements DocumentListener{
        public RepaintDocumentListener(CommonTextBlock par) {
            super();
            parCommonTextBlock = par;
        }
        
        public void removeUpdate(DocumentEvent evt){
            parCommonTextBlock.repaintMainPane();
        }
        
         public void insertUpdate(DocumentEvent e) {
            parCommonTextBlock.repaintMainPane();
        }
        public void changedUpdate(DocumentEvent evt){
            parCommonTextBlock.repaintMainPane();
        }
        
        private CommonTextBlock parCommonTextBlock;
    }

    
    private CommonTextButtonBar commonTextButtonBar;
    private MainWindow parentMainWindow;
    private BlockType curBlockType = BlockType.COMMONTEXT;
    private UndoManager undoManager = new UndoManager();
    
    private BlockBasic inputTextBlockBasic;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane lineNumScrollPane;
    private javax.swing.JTextPane lineNumTextPane;
    private javax.swing.JScrollPane mainInputScrollPane;
    private javax.swing.JTextPane mainInputTextPane;
    // End of variables declaration//GEN-END:variables
}
