/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Blocks;

import javax.swing.JTextPane;

import Bars.ButtonBars.*;
import Start.*;
import javax.swing.undo.UndoManager;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.*;
import java.awt.Color;

/**
 *
 * @author gzy
 */
public class CommonTextBlock extends javax.swing.JPanel {

    /**
     * Creates new form CommonTextBlock
     * @param parentWindow
     */
    public CommonTextBlock(MainWindow parentWindow) {
        initComponents();
        initComponentsManually();
        parentMainWindow = parentWindow;
        inputTextBlockBasic.setMasterInputBlock(this);
    }
    
    public boolean setID(int ID){
        return inputTextBlockBasic.setID(ID);
    }
    
    public int getID(){
        return inputTextBlockBasic.getID();
    }
    
    public boolean changeBlock(BlockType newBlockType){
        return parentMainWindow.changeBlock(inputTextBlockBasic.getID(), newBlockType);
    }
    
    public boolean whetherCanUndo(){
        return undoManager.canUndo();
    }
    
    public boolean whetherCanRedo(){
        return undoManager.canRedo();
    }
    
    public boolean undoOperation(){
        if(!undoManager.canUndo()){
            return false;
        }
        undoManager.undo();
        return true;
    }
    
    public boolean redoOperation(){
        if(!undoManager.canRedo()){
            return false;
        }
        undoManager.redo();
        return true;
    }
    
    public javax.swing.JTextPane getMainTextPane(){
        return mainInputTextPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainInputScrollPane = new javax.swing.JScrollPane();
        mainInputTextPane = new javax.swing.JTextPane();
        lineNumScrollPane = new javax.swing.JScrollPane();
        lineNumEditorPane = new javax.swing.JEditorPane();

        setBackground(new Color(0,0,0,0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 300));

        mainInputScrollPane.setOpaque(false);

        mainInputTextPane.setOpaque(false);
        mainInputScrollPane.setViewportView(mainInputTextPane);

        lineNumScrollPane.setOpaque(false);

        lineNumEditorPane.setOpaque(false);
        lineNumScrollPane.setViewportView(lineNumEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lineNumScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lineNumScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(mainInputScrollPane)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsManually(){
        mainInputScrollPane.getViewport().setOpaque(false);
        lineNumScrollPane.getViewport().setOpaque(false);
        commonTextButtonBar = new CommonTextButtonBar(this);
        commonTextButtonBar.setBounds(0, 0, 650, 62);
        this.add(commonTextButtonBar);
        mainInputTextPane.getDocument().addUndoableEditListener(new UndoableEditListener(){
            public void undoableEditHappened(UndoableEditEvent e){
                undoManager.addEdit(e.getEdit());
            }
        });
    }
    
    private CommonTextButtonBar commonTextButtonBar;
    private MainWindow parentMainWindow;
    private BlockType curBlockType = BlockType.COMMONTEXT;
    private UndoManager undoManager = new UndoManager();
    
    private BlockBasic inputTextBlockBasic = new BlockBasic();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane lineNumEditorPane;
    private javax.swing.JScrollPane lineNumScrollPane;
    private javax.swing.JScrollPane mainInputScrollPane;
    private javax.swing.JTextPane mainInputTextPane;
    // End of variables declaration//GEN-END:variables
}
