/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Blocks;

import javax.swing.text.StyledDocument;
import javax.swing.text.StyledEditorKit;
import javax.swing.text.StyledEditorKit.*;
import javax.swing.text.StyleConstants;
import java.awt.Font;
import java.awt.Color;
import Start.*;

/**
 *
 * @author gzy
 */
public class RichTextBlock extends javax.swing.JPanel {

    /**
     * Creates new form RichTextBlock
     */
    public RichTextBlock(MainWindow parMainWindow) {
        initComponents();
        initComponentsManually();
        parentMainWindow = parMainWindow;
    }
    public String getSelectedText(){
        return mainInputTextPane.getSelectedText();
    }
    
    public int getCaretPosition(){
        return mainInputTextPane.getCaretPosition();
    }
    
    public boolean replaceSelection(String newString){
        mainInputTextPane.replaceSelection(newString);
        return true;
    }
    
    public StyledDocument getStyledDocument(){
        return mainInputTextPane.getStyledDocument();
    }
    
    private void initComponentsManually(){
        richTextToolBox.setBounds(1, 62, 80, 300);
        richTextBlockBasic.setMasterRichTextBlock(this);
        mainInputTextPane.setEditorKit(editorKit);
    }
    
    public StyledEditorKit getEditorKit(){
        editorKit = new StyledEditorKit();
        return editorKit;
    }
    
    public StyledEditorKit.AlignmentAction getAlignmentAction(int alignType){
        alignAction = new StyledEditorKit.AlignmentAction("Alignment",alignType);
        return alignAction;
    }
    
    public StyledEditorKit.BoldAction getBoldAction(){
        boldAction = new StyledEditorKit.BoldAction();
        return boldAction;
    }
    
    public StyledEditorKit.CopyAction getCpyAction(){
        cpyAction = new StyledEditorKit.CopyAction();
        return cpyAction;
    }
    
    public StyledEditorKit.CutAction getCutAction(){
        cutAction = new StyledEditorKit.CutAction();
        return cutAction;
    }
    
    public StyledEditorKit.PasteAction getPasteAction(){
        pasteAction = new StyledEditorKit.PasteAction();
        return pasteAction;
    }
    
    public StyledEditorKit.FontFamilyAction getFontFamilyAction(String fontFamily){
        fontFamilyAction = new StyledEditorKit.FontFamilyAction("font",fontFamily);
        return fontFamilyAction;
    }
    
    public StyledEditorKit.FontSizeAction getFontSizeAction(int size){
        fontSizeAction = new StyledEditorKit.FontSizeAction("size",size);
        return fontSizeAction;
    }
    
    public StyledEditorKit.ForegroundAction getForegroundAction(Color color){
        fontColorAction = new StyledEditorKit.ForegroundAction("color",color);
        return fontColorAction;
    }
    
    public StyledEditorKit.ItalicAction getItalicAction(){
        italicAction = new StyledEditorKit.ItalicAction();
        return italicAction;
    }
    
    public StyledEditorKit.UnderlineAction getUnderlineAction(){
        underlineAction = new StyledEditorKit.UnderlineAction();
        return underlineAction;
    }
    
    public BlockBasic getBlockBasic(){
        return richTextBlockBasic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainInputScrollPane = new javax.swing.JScrollPane();
        mainInputTextPane = new javax.swing.JTextPane();
        lineNumScrollPane = new javax.swing.JScrollPane();
        lineNumEditorPane = new javax.swing.JEditorPane();

        setOpaque(false);
        setSize(new java.awt.Dimension(1200, 300));

        mainInputScrollPane.setOpaque(false);

        mainInputTextPane.setOpaque(false);
        mainInputScrollPane.setViewportView(mainInputTextPane);

        lineNumScrollPane.setOpaque(false);

        lineNumEditorPane.setOpaque(false);
        lineNumScrollPane.setViewportView(lineNumEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(lineNumScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lineNumScrollPane)
                    .addComponent(mainInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private RichTextToolBox richTextToolBox = new RichTextToolBox(this);
    private MainWindow parentMainWindow;
    private BlockBasic richTextBlockBasic = new BlockBasic();
    private StyledEditorKit editorKit;
    private StyledEditorKit.AlignmentAction alignAction;
    private StyledEditorKit.BoldAction boldAction;
    private StyledEditorKit.CopyAction cpyAction;
    private StyledEditorKit.CutAction cutAction;
    private StyledEditorKit.PasteAction pasteAction;
    private StyledEditorKit.FontFamilyAction fontFamilyAction;
    private StyledEditorKit.FontSizeAction fontSizeAction;
    private StyledEditorKit.ForegroundAction fontColorAction;
    private StyledEditorKit.ItalicAction italicAction;
    private StyledEditorKit.UnderlineAction underlineAction;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane lineNumEditorPane;
    private javax.swing.JScrollPane lineNumScrollPane;
    private javax.swing.JScrollPane mainInputScrollPane;
    private javax.swing.JTextPane mainInputTextPane;
    // End of variables declaration//GEN-END:variables
}
