/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Blocks;

import javax.swing.text.*;

/**
 *
 * @author gzy
 */
public class RichTextToolBox extends javax.swing.JPanel {

    /**
     * Creates new form RichTextToolBox
     */
    public RichTextToolBox(RichTextBlock parBlock) {
        initComponents();
        parentRichTextBlock = parBlock;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        increaseFontSizeButton = new javax.swing.JButton();
        changeFontButton = new javax.swing.JButton();
        changeColorButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        changeFormButton = new javax.swing.JButton();
        fontComboBox = new javax.swing.JComboBox<>();
        formComboBox = new javax.swing.JComboBox<>();
        boldButton = new javax.swing.JButton();
        italyButton = new javax.swing.JButton();
        underlineButton = new javax.swing.JButton();
        deleteLine = new javax.swing.JButton();
        decreaseFontSizeButton1 = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(80, 300));

        increaseFontSizeButton.setText("A+");
        increaseFontSizeButton.setPreferredSize(new java.awt.Dimension(75, 29));
        increaseFontSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseFontSizeButtonActionPerformed(evt);
            }
        });

        changeFontButton.setText("Font");
        changeFontButton.setPreferredSize(new java.awt.Dimension(75, 29));
        changeFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontButtonActionPerformed(evt);
            }
        });

        changeColorButton.setText("Color");
        changeColorButton.setPreferredSize(new java.awt.Dimension(75, 29));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IDLE", "Blue", "Green", "Red", "Yellow" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(75, 27));
        jComboBox1.setPreferredSize(new java.awt.Dimension(75, 27));
        jComboBox1.setSize(new java.awt.Dimension(75, 27));

        changeFormButton.setText("Form");
        changeFormButton.setPreferredSize(new java.awt.Dimension(75, 29));

        fontComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PingFang", "Source Code Pro" }));
        fontComboBox.setMinimumSize(new java.awt.Dimension(75, 27));
        fontComboBox.setPreferredSize(new java.awt.Dimension(75, 27));
        fontComboBox.setSize(new java.awt.Dimension(75, 27));

        formComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mid Align", "Left Align", "Right Align", "First line indent" }));
        formComboBox.setMinimumSize(new java.awt.Dimension(75, 27));
        formComboBox.setPreferredSize(new java.awt.Dimension(75, 27));
        formComboBox.setSize(new java.awt.Dimension(75, 27));

        boldButton.setText("B");
        boldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boldButtonActionPerformed(evt);
            }
        });

        italyButton.setText("I");

        underlineButton.setText("U");

        deleteLine.setText("D");

        decreaseFontSizeButton1.setText("A-");
        decreaseFontSizeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseFontSizeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(underlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(increaseFontSizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(italyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteLine, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseFontSizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(changeFontButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(changeFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(formComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(changeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(italyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(underlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(increaseFontSizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseFontSizeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeFontButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeFontButtonActionPerformed

    private void increaseFontSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseFontSizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseFontSizeButtonActionPerformed

    private void decreaseFontSizeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseFontSizeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseFontSizeButton1ActionPerformed

    private void boldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boldButtonActionPerformed

    private RichTextBlock parentRichTextBlock;
    
    private int index;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boldButton;
    private javax.swing.JButton changeColorButton;
    private javax.swing.JButton changeFontButton;
    private javax.swing.JButton changeFormButton;
    private javax.swing.JButton decreaseFontSizeButton1;
    private javax.swing.JButton deleteLine;
    private javax.swing.JComboBox<String> fontComboBox;
    private javax.swing.JComboBox<String> formComboBox;
    private javax.swing.JButton increaseFontSizeButton;
    private javax.swing.JButton italyButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton underlineButton;
    // End of variables declaration//GEN-END:variables
}
