/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bars.ButtonBars;

import Blocks.BlockType;
import static Blocks.BlockType.BLANK;
import static Blocks.BlockType.CODE;
import static Blocks.BlockType.COMMONTEXT;
import static Blocks.BlockType.FORMULA;
import static Blocks.BlockType.IMAGE;
import static Blocks.BlockType.MARKDOWN;
import static Blocks.BlockType.MEDIA;
import static Blocks.BlockType.RICHTEXT;
import static Blocks.BlockType.TABLE;
import static Blocks.BlockType.TITLE;
import static Blocks.BlockType.VIDEO;
import static Blocks.BlockType.HYPERTEXT;

import Start.*;

/**
 *
 * @author gzy
 */
public class MainWindowButtonBar extends javax.swing.JPanel {

    /**
     * Creates new form MainWindowButtonBar
     */
    public MainWindowButtonBar(MainWindow parent) {
        initComponents();
        parentMainWindow = parent;
    }
        
    private BlockType getNewBlockType(int comboxIndex){
        switch(comboxIndex){
            case 0->{
                return COMMONTEXT;
            }
            case 1->{
                return CODE;
            }
            case 2->{
                return HYPERTEXT;
            }
            case 3->{
                return MARKDOWN;
            }
            case 4->{
                return FORMULA;
            }
            case 5->{
                return RICHTEXT;
            }
            case 6->{
                return TITLE;
            }
            case 7->{
                return IMAGE;
            }
            case 8->{
                return VIDEO;
            }
            case 9->{
                return TABLE;
            }
            default->{
                return BLANK;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appendBlockButton = new javax.swing.JButton();
        popBlockButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        previewButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        doSearchButton = new javax.swing.JButton();
        doReplaceButton = new javax.swing.JButton();
        replaceAllButton = new javax.swing.JButton();
        blockTypeComboBox = new javax.swing.JComboBox<>();

        setOpaque(false);

        appendBlockButton.setText("Append Block (+)");
        appendBlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendBlockButtonActionPerformed(evt);
            }
        });

        popBlockButton.setText("Pop Block (-)");
        popBlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBlockButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");

        exportButton.setLabel("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        previewButton.setLabel("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        doSearchButton.setText("Search");

        doReplaceButton.setText("Replace");
        doReplaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doReplaceButtonActionPerformed(evt);
            }
        });

        replaceAllButton.setText("Replace All");

        blockTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Common Text", "Code", "HyperText", "Markdown", "Formula", "Rich Text", "Infinite Title", "Image", "Video", "Table", "Blank" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appendBlockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(popBlockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doReplaceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previewButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appendBlockButton)
                    .addComponent(popBlockButton)
                    .addComponent(importButton)
                    .addComponent(exportButton)
                    .addComponent(previewButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doSearchButton)
                    .addComponent(doReplaceButton)
                    .addComponent(replaceAllButton)
                    .addComponent(blockTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportButtonActionPerformed

    private void doReplaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doReplaceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doReplaceButtonActionPerformed

    private void appendBlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendBlockButtonActionPerformed
        // TODO add your handling code here:
        parentMainWindow.appendBlock(getNewBlockType(blockTypeComboBox.getSelectedIndex()));
    }//GEN-LAST:event_appendBlockButtonActionPerformed

    private void popBlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popBlockButtonActionPerformed
        // TODO add your handling code here:
        parentMainWindow.popBlock();
    }//GEN-LAST:event_popBlockButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        // TODO add your handling code here:
        parentMainWindow.preview();
    }//GEN-LAST:event_previewButtonActionPerformed

    private MainWindow parentMainWindow;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appendBlockButton;
    private javax.swing.JComboBox<String> blockTypeComboBox;
    private javax.swing.JButton doReplaceButton;
    private javax.swing.JButton doSearchButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton importButton;
    private javax.swing.JButton popBlockButton;
    private javax.swing.JButton previewButton;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
