/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Bars.ButtonBars;

/**
 *
 * @author gzy
 */
public class OutputAreaButtonBar extends javax.swing.JPanel {

    /**
     * Creates new form OutputAreaButtonBar
     */
    public OutputAreaButtonBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeLabel = new javax.swing.JLabel();
        useDirectlyButton = new javax.swing.JButton();
        hideButton = new javax.swing.JButton();
        showButton = new javax.swing.JButton();
        editHtmlButton = new javax.swing.JButton();

        setOpaque(false);

        typeLabel.setText("Block Output Area");

        useDirectlyButton.setText("Use Directly");
        useDirectlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDirectlyButtonActionPerformed(evt);
            }
        });

        hideButton.setText("Hide");
        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        showButton.setText("Show");

        editHtmlButton.setText("Edit Html");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(hideButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editHtmlButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useDirectlyButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(typeLabel)
                .addComponent(useDirectlyButton)
                .addComponent(hideButton)
                .addComponent(showButton)
                .addComponent(editHtmlButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useDirectlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDirectlyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useDirectlyButtonActionPerformed

    private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hideButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editHtmlButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton useDirectlyButton;
    // End of variables declaration//GEN-END:variables
}
